language: node_js
node_js:
  - "0.10"
  - "0.11"
before_script:
  - psql -c 'create database webmention_test;' -U postgres
script: npm run travis
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
addons:
  postgresql: "9.3"
